### ISSUE TITLE
Missing paper_figures notebooks requirements

### ISSUE THREAD

**Issue by ckarageorgkaneen** [Poirazi-Lab/dendrify#11] opened 2023-01-27 03:37 UTC
In order to successfully run the `paper_figures/` notebooks , I had to manually install the following requirements:

```
git-lfs
networkx
seaborn
scipy
statsmodels
```

These should either be installed at the top of the notebook (e.g. `!pip install seaborn --quiet`), or at least be inside a `paper_figures/requirements.txt` file, so a user can easily install them all at once.

**Comment by ckarageorgkaneen** [comment] 2023-01-28 22:24
See See https://github.com/Poirazi-Lab/dendrify/blob/main/paper_figures/Fig5_notebook.ipynb. Runs fine in colab, but locally I had to install some packages manually.

**Comment by mpgl** [comment] 2023-01-29 15:09
Thank you @ckarageorgkaneen for pointing this out. However since this notebook is supposed to run online through Google colab (to reproduce the paper’s figures), I don’t think it’s a problem. Soon, I will release some tutorials and code examples that won’t need any dependencies installation apart from Brian and Dendrify. I am closing this issue, but in case you come across any similar problems please let me know. Thanks.

**Closed by mpgl** 2023-01-29 15:09 UTC
